services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3141:80/tcp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - ServerIP=${PIHOLE_HOST_IP}
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
