---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homelab

background:
  image: https://cdna.artstation.com/p/assets/images/images/006/102/120/large/vadim-sadovski-f25.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

useEqualHeights: true

layout:
  Hypervisor:
    header: true
    style: row
    columns: 4
  Network:
    header: true
    style: row
    columns: 4
  Containers:
    header: true
    style: row
    columns: 4
  Storage:
    header: true
    style: row
    columns: 4
  Apps:
    header: true
    style: row
    columns: 4
